In [1]:
a variable = 34

SyntaxError: invalid syntax (<ipython-input-1-021a1139ac80>, line 1)

In [2]:
my-fav-car= "Nano"

SyntaxError: can't assign to operator (<ipython-input-2-7e7cd0f87ae9>, line 1)

# Matrix Multiplication

In [2]:
 import numpy as np
 import pandas as pd   
   
climate_data = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12],
    [13, 14, 15]
])

In [4]:
climate_data

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [42]:
weights = np.array([12,3,15])

In [43]:
weights

array([12,  3, 15])

In [7]:
np.matmul(climate_data, weights)

array([ 63, 153, 243, 333, 423])

In [8]:
climate_data @ weights

array([ 63, 153, 243, 333, 423])

# Working with CSV File Data

In [33]:
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7fe9b9c6d7b8>)

In [34]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)


In [35]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [36]:
climate_data.shape

(10000, 3)

In [37]:
climate = np.genfromtxt('climate.txt', delimiter=',')

In [38]:
climate.shape

(10001, 3)

In [39]:
climate

array([[nan, nan, nan],
       [25., 76., 99.],
       [39., 65., 70.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [22]:
import numpy as np
import pandas as pd



# Assign column names
column_names = ["temp", "rainfall", "humidity"]

# Create a DataFrame
my_dataframe = pd.DataFrame(climate, columns=column_names)

# Display the DataFrame
print(my_dataframe.head())

   temp  rainfall  humidity
0   NaN       NaN       NaN
1  25.0      76.0      99.0
2  39.0      65.0      70.0
3  59.0      45.0      77.0
4  84.0      63.0      38.0


In [23]:
my_dataframe

temp  rainfall  humidity
0       NaN       NaN       NaN
1      25.0      76.0      99.0
2      39.0      65.0      70.0
3      59.0      45.0      77.0
4      84.0      63.0      38.0
...     ...       ...       ...
9996   80.0      72.0      98.0
9997   27.0      58.0      60.0
9998   99.0      62.0      58.0
9999   70.0      71.0      91.0
10000  92.0      39.0      76.0

[10001 rows x 3 columns]

In [26]:
my_dataframe.to_csv('climate_txt.csv')

In [27]:
weights = np.array([0.3,0.2,0.5])

In [28]:
weights

array([0.3, 0.2, 0.5])

In [42]:
 yeilds = climate_data @ weights  # cross multiplicataion of 2 matrix

In [43]:
yeilds.shape


(10000,)

In [50]:
a = np.array([[1, 2], 
                 [5, 6] ])


In [45]:
b = np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18]])

In [51]:
a.shape


(2, 2)

In [49]:
b.shape

(2, 4)

In [54]:
 np.concatenate((a,b), axis= 1)

array([[ 1,  2, 11, 12, 13, 14],
       [ 5,  6, 15, 16, 17, 18]])

In [58]:
climate_result = np.concatenate((climate_data,yeilds.reshape(10000,1)), axis=1  )

In [59]:
climate_result

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

### Mathematics: np.sum, np.exp, np.round, arithemtic operators
### Array manipulation: np.reshape, np.stack, np.concatenate, np.split
### Linear Algebra: np.matmul, np.dot, np.transpose, np.eigvals
### Statistics: np.mean, np.median, np.std, np.max

# Arithmetic Operation and Broadcasting

In [3]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])


In [4]:
              
arr3 = np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18], 
                 [19, 11, 12, 13]])

In [5]:
arr2*arr3

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

In [6]:
arr2+2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11,  3,  4,  5]])

In [7]:
arr3-arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [8]:
arr2/2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 0.5, 1. , 1.5]])

In [10]:
arr2%4

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 1, 2, 3]])

In [11]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [12]:
arr2.shape

(3, 4)

In [13]:
arr4 = np.array([4,5,6,7])

In [15]:
arr4.shape

(4,)

In [16]:
arr2+arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [20]:
# 2 x 3 X 2 
arr1 = np.array([[[1,2],
         [3,4],
         [5,6]],
        [[7,8],
        [9,10],
        [11,12]
        
        
        ]])

In [22]:
arr1

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [23]:
arr1.shape

(2, 3, 2)

In [24]:
arr2 = np.array([5,6])

In [26]:
arr2.shape

(2,)

In [29]:
# shapes
# arr1--- 2X3X2
# arr2--------2   this willl become 2x3x2  automatically

In [30]:
arr1+arr2

array([[[ 6,  8],
        [ 8, 10],
        [10, 12]],

       [[12, 14],
        [14, 16],
        [16, 18]]])

In [31]:
arrr5 = np.array([5,6,7])

In [33]:
arr1+arr5  # arr5 has not a compatible dimension

NameError: name 'arr5' is not defined

In [34]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])

In [35]:
arr1 ==arr2

array([[False,  True,  True],
       [False, False,  True]])

In [36]:
arr1 != arr2

array([[ True, False, False],
       [ True,  True, False]])

In [37]:
arr1>=arr2

array([[False,  True,  True],
       [ True,  True,  True]])

In [38]:
arr1<arr2

array([[ True, False, False],
       [False, False, False]])

In [39]:
(arr1 ==arr2).sum()

3

In [40]:
np.sum(arr1 ==arr2)

3

# Array indexing and Slicing

In [49]:
weight = np.array([0.3, 0.2, 0.5])


In [53]:
weight[1]

'0.2'

In [54]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

In [56]:
# subarray using ranges
arr3.shape


(3, 2, 4)

In [57]:
arr3[1:, 0:1]

array([[[15., 16., 17., 21.]],

       [[98., 32., 81., 23.]]])

In [60]:
arr3[0,1,1]

14.0

array([18., 43.])

In [61]:
arr3[1:,1,3]

array([18., 43.])

In [64]:
arr3[1,3,2,1]  # not a 4 diensional


IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed

# other ways of create Array

In [68]:
# All zeros
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [69]:
np.ones([2,2,3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [70]:
# identity MAtrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [71]:
np.random.rand(5)

array([0.65672077, 0.51387448, 0.74252772, 0.51368281, 0.07586058])

In [72]:
np.random.randn(2,3)

array([[-1.41081083,  1.14906445,  0.28717592],
       [-0.15150382,  0.72866176,  0.24376601]])

In [73]:
np.full([2,3],42)

array([[42, 42, 42],
       [42, 42, 42]])

In [75]:
# Range with start , end and step
np.arange(10,90,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [76]:
np.arange(10,90,3).reshape(3,3,3)

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

In [78]:
# equally spaced numbers in a range
np.linspace(3,27,12)

array([ 3.        ,  5.18181818,  7.36363636,  9.54545455, 11.72727273,
       13.90909091, 16.09090909, 18.27272727, 20.45454545, 22.63636364,
       24.81818182, 27.        ])

# Save and Commit