In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import aws_connection
sw = aws_connection.get_connection()

In [2]:
#df = pd.read_sql(f'''  select * from  loan_application limit 90''', sw)

# Data Structure


# 1. Lists:
####  Lists are ordered, mutable (modifiable), and can store elements of different data types. They are enclosed in square brackets [ ] and support indexing and slicing to access elements.

In [3]:
# Creating a list
Emp = ['Jitu', 'Shivani', 'Rani', 'Sambit']
print(Emp)
# Accessing elements
print(Emp[0])    # Output: 'apple'
print(Emp[1:])   # Output: ['banana', 'orange', 'grape']

# Modifying elements
Emp[2] = 'kiwi'
print(Emp)       # Output: ['apple', 'banana', 'kiwi', 'grape']

# Adding elements
Emp.append('mango')
print(Emp)       # Output: ['apple', 'banana', 'kiwi', 'grape', 'mango']

# Removing elements
Emp.remove('Sambit')
print(Emp)       # Output: ['apple', 'kiwi', 'grape', 'mango']


['Jitu', 'Shivani', 'Rani', 'Sambit']
Jitu
['Shivani', 'Rani', 'Sambit']
['Jitu', 'Shivani', 'kiwi', 'Sambit']
['Jitu', 'Shivani', 'kiwi', 'Sambit', 'mango']
['Jitu', 'Shivani', 'kiwi', 'mango']


In [4]:
Table1 = [1,2,3,4,5,6,11]
Table2 = [7,8,9,10]

In [5]:
Table1 + Table2

[1, 2, 3, 4, 5, 6, 11, 7, 8, 9, 10]

In [6]:
Table1*2

[1, 2, 3, 4, 5, 6, 11, 1, 2, 3, 4, 5, 6, 11]

In [84]:
my_list = [1, 2, 3, 4, 5]

In [8]:
my_list.append(6)  #to add an element at the end of the list

In [9]:
my_list

[1, 2, 3, 4, 5, 6]

In [10]:
my_list.insert(2, 10)  # Inserts 7 at index 2

In [85]:
my_list

[1, 2, 3, 4, 5]

In [12]:
my_list[1] = 8  # Updates the element at index 1 to 8

In [13]:
my_list

[1, 8, 10, 3, 4, 5, 6]

In [86]:
my_list.remove(5)  # Removes the element with the value 5
popped_element = my_list.pop(2)  # Removes and returns the element at index 2


In [87]:
popped_element

3

In [89]:
my_list


[1, 2, 4]

In [17]:
index = my_list.index(3)  # Finds the index of the element with the value 3


In [18]:
index

2

In [19]:
sub_list = my_list[1:4]  # Creates a sub-list from index 1 to 3  (not include last wala index)
sub_list

[8, 3, 4]

In [20]:
length = len(my_list)
length

5

In [21]:
my_list.sort()  # Sorts the list in ascending order
sorted_list = sorted(my_list)  # Creates a new sorted list
sorted_list

[1, 3, 4, 6, 8]

In [22]:
my_list.reverse()  # Reverses the order of elements
my_list

[8, 6, 4, 3, 1]

In [23]:
exists = 10 in my_list  # Checks if 3 is in the list
exists

False

In [4]:
lst =  [i*i for i in range(10)]
print(lst)

lst = [i*i for i in range(10) if i%2==0]
print(lst)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 4, 16, 36, 64]


# 2.Tuples:
#### Tuples are ordered, immutable (cannot be changed after creation), and use parentheses ( ) to define elements. They are useful for representing fixed collections of items.

In [18]:
tup = (1,2)
print(type(tup),tup)

<class 'tuple'> (1, 2)


In [20]:
tup[0]=90

TypeError: 'tuple' object does not support item assignment

In [47]:
tup.append(8)

AttributeError: 'tuple' object has no attribute 'append'

In [23]:
tupp= (1,2,3,40,90,"Daria", True)
print(type(tupp), tupp)
print(len(tupp), tupp)
print(tupp[0])
print(tupp[2])
print(tupp[-2])





<class 'tuple'> (1, 2, 3, 40, 90, 'Daria', True)
7 (1, 2, 3, 40, 90, 'Daria', True)
1
3
Daria


In [40]:
if 900 in tupp:
    print("yes, 90 is present in tupp")
else:
    print("no")

no


In [29]:
#Creating a tuple
point = (10, 20,30,40)
#Accessing elements
print(point[2])     # Output: 10

#Tuples are immutable, so the following line will raise an error:
#point[0] = 5


30


In [25]:
point*2   # append 2 times

(10, 20, 30, 40, 10, 20, 30, 40)

In [55]:
tup2 = tupp[1:3]
print(tup2)

(2, 3)


In [51]:
countries= ("India", "Aus", "England")
countries2= ("SA", "USA", "UK")
new= countries+ countries2  # merge both the tuples
print (new)

('India', 'Aus', 'England', 'SA', 'USA', 'UK')


In [59]:
print(tup2.count(2))  # gives occurances of the 2 element in th tup2
print(tup2.index(2))  # gives indexing of the 2 element in th tup2

1
0


In [61]:
tuple3 = (1,2,3,4,4,4,5,7,9,1,3,5,6,2)
res = tuple3.index(3,2,9)
print("count of 3 in tuple3 bw index 2 and 9: ", res)

count of 3 in tuple3 bw index 2 and 9:  2


In [92]:
country= ("India", "Aus", "England", "Italy", "Turkey")
temp = list(country)
temp.append("Russia")
temp.pop(3)
print(temp)

['India', 'Aus', 'England', 'Turkey', 'Russia']


# 3.Dictionaries:
#### Dictionaries are unordered, mutable, and store data in key-value pairs. They use curly braces { } to define elements, with each key-value pair separated by a colon (:).

In [26]:
# Creating a dictionary
student = {'emp': 'Jitu', 'age': 25, 'grade': 'A','name': 'John' }


# Accessing elements
print(student['name'])   # Output: 'John'

# Modifying elements
student['age'] = 26
print(student)           # Output: {'name': 'John', 'age': 26, 'grade': 'A'}

# Adding elements
student['school'] = 'ABC High School'
print(student)           # Output: {'name': 'John', 'age': 26, 'grade': 'A', 'school': 'ABC High School'}

# Removing elements
del student['grade']
print(student)           # Output: {'name': 'John', 'age': 26, 'school': 'ABC High School'}


John
{'emp': 'Jitu', 'age': 26, 'grade': 'A', 'name': 'John'}
{'emp': 'Jitu', 'age': 26, 'grade': 'A', 'name': 'John', 'school': 'ABC High School'}
{'emp': 'Jitu', 'age': 26, 'name': 'John', 'school': 'ABC High School'}


In [27]:
# Example of a nested dictionary
employee_data = {
    'John': {
        'age': 30,
        'position': 'Manager',
        'salary': 50000  },
    'Alice': {
        'age': 25,
        'position': 'Developer',
        'salary': 40000 },
    'Bob': {
        'age': 28,
        'position': 'Designer',
        'salary': 45000},
    'Jitu': {
        'age': 25,
        'position': 'Analyst',
        'salary': 60000}   }

# Accessing elements in the nested dictionary
print(employee_data['Jitu']['position'])   
print(employee_data['Alice']['age'])      

# Modifying elements in the nested dictionary
employee_data['Jitu']['salary'] = 90000
print(employee_data['Jitu']['salary'])    

# Adding new employee to the nested dictionary
employee_data['Eva'] = {
    'age': 35,
    'position': 'HR',
    'salary': 42000
}
print(employee_data['Eva'])              

# Deleting elements in the nested dictionary
del employee_data['Alice']['position']
print(employee_data['Alice'])       


# modifications
employee_data['age'] = 50
print(employee_data['Eva']['age'])


Analyst
25
90000
{'age': 35, 'position': 'HR', 'salary': 42000}
{'age': 25, 'salary': 40000}
35


# 4.Sets:
#### Sets are unordered and mutable collections of unique elements. They use curly braces { } or the set() function to define elements. Sets are useful for removing duplicates and performing set operations like union, intersection, etc.

In [28]:
# Creating a set
fruits_set = {'apple', 'banana', 'orange', 'apple'}

# Duplicates are automatically removed
print(fruits_set)        # Output: {'apple', 'banana', 'orange'}

# Set operations
set1 = {1, 2, 3}
set2 = {3, 4, 5}

print(set1 .union(set2))       # Output: {1, 2, 3, 4, 5}
print(set1.intersection(set2))  # Output: {3}


{'banana', 'apple', 'orange'}
{1, 2, 3, 4, 5}
{3}


In [29]:
# fruits_set[2]   set doesnot support indexing


In [30]:
set1.add(10)

In [31]:
set1

{1, 2, 3, 10}

In [32]:
set1.add('jitu')

In [33]:
set1

{1, 10, 2, 3, 'jitu'}

In [34]:
print(set1.union(set2))

{1, 2, 3, 4, 5, 'jitu', 10}


In [45]:
df.shape                                           

(5, 2)

In [46]:
df.columns      

Index(['A', 'B'], dtype='object')

In [ ]:
df.to_csv('loanbills.csv')                         

In [40]:
 import numpy as np

# Creating a 1-D array
one_dimensional_array = np.array([1, 2, 3, 4, 5])

# Accessing elements of a 1-D array
print(one_dimensional_array[0])  # Access the first element
print(one_dimensional_array[2])  # Access the third element

# Perform operations on 1-D array
result = one_dimensional_array + 2
print(result)  # Adds 2 to each element

# Perform operations on 1-D array
result2 = np.append(one_dimensional_array, 2)
print(result2)

# Calculate the mean of the elements
mean = np.mean(one_dimensional_array)
print(mean)

1
3
[3 4 5 6 7]
[1 2 3 4 5 2]
3.0


In [38]:

# Creating a 2-D array (matrix)
two_dimensional_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing elements of a 2-D array
print(two_dimensional_array[0, 0])  # Access the element in the first row and first column
print(two_dimensional_array[1, 2])  # Access the element in the second row and third column

# Perform operations on 2-D array
result = two_dimensional_array * 2  # Multiply each element by 2
print(result)

# Calculate the sum of all elements
sum_all = np.sum(two_dimensional_array)
print(sum_all)


# Calculate the mean of the elements
mean = np.mean(two_dimensional_array)
print(mean)

1
6
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
45
5.0


In [63]:
import pandas as pd

# Creating two sample DataFrames
df1 = pd.DataFrame({'A': [1, 2, 3, 4],
                    'B': ['a', 'b', 'c', 'd']})

df2 = pd.DataFrame({'A': [3, 4, 5, 6],
                    'C': ['x', 'y', 'z', 'w']})

# Performing different types of joins
# Inner Join
inner_join = pd.merge(df1, df2, on='A', how='inner')

# Left Join
left_join = pd.merge(df1, df2, on='A', how='left')

# Right Join
right_join = pd.merge(df1, df2, on='A', how='right')

# Outer Join
outer_join = pd.merge(df1, df2, on='A', how='outer')

# Displaying the results
print("Inner Join:")
print(inner_join)

print("\nLeft Join:")
print(left_join)

print("\nRight Join:")
print(right_join)

print("\nOuter Join:")
print(outer_join)


Inner Join:
   A  B  C
0  3  c  x
1  4  d  y

Left Join:
   A  B    C
0  1  a  NaN
1  2  b  NaN
2  3  c    x
3  4  d    y

Right Join:
   A    B  C
0  3    c  x
1  4    d  y
2  5  NaN  z
3  6  NaN  w

Outer Join:
   A    B    C
0  1    a  NaN
1  2    b  NaN
2  3    c    x
3  4    d    y
4  5  NaN    z
5  6  NaN    w


In [1]:
import pandas as pd

# Creating a sample DataFrame
data = {'A': [1, 2, 3, 4, 5],
        'B': [6, 7, 8, 9, 10]}

df = pd.DataFrame(data, index=['a', 'b', 'c', 'd', 'e'])

# Using loc to access data by label
print("Using loc:")
print(df.loc['a', 'A'])  # Accessing a single element

# Using iloc to access data by integer index
print("\nUsing iloc:")
print(df.iloc[0, 0])  # Accessing a single element


Using loc:
1

Using iloc:
1


## STRING DATA TYPE

In [3]:
name = "jiten"
friend = "shivani"
anotherfriend= "rani"
print("hello,",name)

hello, jiten


In [6]:
apple = '''   He said,

Hi Daria
I am good 
"I want to eat an apple"

'''

print("Helllo, " +apple)

Helllo,    He said,

Hi Daria
I am good 
"I want to eat an apple"




In [7]:
print(apple)

   He said,

Hi Daria
I am good 
"I want to eat an apple"




In [8]:
str = """name = "jiten"
friend = "shivani"
anotherfriend= "rani"
print("hello,",name)

apple = '''   He said,

Hi Daria
I am good 
"I want to eat an apple"

'''

print("Helllo, " +apple)"""

print(str)


name = "jiten"
friend = "shivani"
anotherfriend= "rani"
print("hello,",name)

apple = '''   He said,

Hi Daria
I am good 
"I want to eat an apple"

'''

print("Helllo, " +apple)


In [11]:
print(name[0])
print(name[1])
print(name[3])
print(name[4])

j
i
e
n


In [12]:
for character in name:
    print(character)

j
i
t
e
n


In [15]:
print(len(apple))

59
